<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ECommerce.Domain\ECommerce.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="SharpGrip.FluentValidation.AutoValidation.Mvc" Version="2.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Contracts\Category\" />
    <Folder Include="Features\Categories\Commands\Validators\" />
    <Folder Include="Features\Categories\Queries\Requests\" />
    <Folder Include="Features\Products\Queries\Handlers\" />
    <Folder Include="Interfaces\Services\" />
  </ItemGroup>

</Project>
